name: Dan Middleton
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51554
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.48084950912743807
  lightness: 0.6481716844718903
  saturation: 0.5083248023875058
  rhythmicContrast: 0.11652752803638577
purpose: []
